# Generated by Django 2.2 on 2019-08-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo'),
        ),
    ]
