# Generated by Django 2.2 on 2019-09-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_announcement_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='pdf_file',
        ),
    ]
