# Generated by Django 2.2 on 2019-06-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='formation', verbose_name='Imagen'),
        ),
    ]
