# Generated by Django 2.2 on 2019-06-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'inicio', 'verbose_name_plural': 'inicio'},
        ),
        migrations.AlterField(
            model_name='home',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
    ]
