# Generated by Django 2.2 on 2019-06-11 22:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190610_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
