# Generated by Django 2.2 on 2019-06-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'nosotros', 'verbose_name_plural': 'somos'},
        ),
    ]
